// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EliMZ_Book","status":true,"description":"♦5.4.17♦ Essential plugin for all Eli plugins.","parameters":{"engine":"{\"pixelPerfect\":\"false\",\"styleOverflow\":\"false\",\"--- MZ ONLY ---\":\"\",\"disableEffekseer\":\"false\"}","playtest":"{\"openDevTools\":\"false\",\"nwWindowPos\":\"0, 0\",\"--- MZ ONLY ---\":\"\",\"gameFocus\":\"true\",\"quickRestart\":\"true\"}"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"EliMZ_EnemyClass","status":true,"description":"♦5.2.0♦ Add class, equips, level and exp to Enemies!","parameters":{"equipRules":"false","actionPatternMode":"true","defaultActionRating":"5"}},
{"name":"EliMZ_MobileControls","status":true,"description":"♦5.2.0♦ Add responsive on screen controls to mobile games!","parameters":{"allowedPlatforms":"[]","disableScreenMove":"true","disableDoubleTouchMenu":"true","hideOnMessage":"false","fixButtonSize":"false","fixButtonInterval":"120","controlButton":"{\"enable\":\"false\",\"img\":\"\",\"width\":\"5\",\"horizontalOrientation\":\"left\",\"padX\":\"2\",\"verticalOrientation\":\"top\",\"padY\":\"2\",\"vibration\":\"0\",\"enableScreenMove\":\"true\",\"enableDoubleTouchMenu\":\"true\"}","buttons":"[]","dPadType":"singlePad","singlePad":"{\"scenes\":\"[]\",\"img\":\"\",\"baseWidth\":\"20\",\"horizontalOrientation\":\"left\",\"padX\":\"2\",\"verticalOrientation\":\"bottom\",\"padY\":\"2\"}","joystickPad":"{\"scenes\":\"[]\",\"baseImg\":\"\",\"baseWidth\":\"20\",\"ballImg\":\"\",\"ballWidth\":\"4\",\"extraDistance\":\"0\",\"horizontalOrientation\":\"left\",\"padX\":\"2\",\"verticalOrientation\":\"bottom\",\"padY\":\"2\"}"}},
{"name":"screenWidthHeight","status":true,"description":"","parameters":{}}
];
